apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pod
      namespace: chat-app
      labels: 
        app: frontend
    spec:
      containers:
      - name: chatapp-frontend
        image: syedabdullahahmed/new-chatapp-frontend:26
        ports:
        - containerPort: 5173
        env:
        - name: NODE_ENV
          value: production
        - name: VITE_APP_URL
          # value: http://backend.chat-app.svc.cluster.local:5001 # for internal svc if alb not needed
          value: http://k8s-chatapp-96bfa4e77f-974437340.us-east-1.elb.amazonaws.com # if alb needed
          



